// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFSyZJbJwuRk1HVZjx-QKwQjHRVA1Sx4',
    appId: '1:1049388848315:android:ae9be7f8d564fe4580859e',
    messagingSenderId: '1049388848315',
    projectId: 'fir-casa0015-app',
    storageBucket: 'fir-casa0015-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZonXoF6YVTliAcj4TZj_sJAC1sIOQ43Y',
    appId: '1:1049388848315:ios:a91696f887c3a26080859e',
    messagingSenderId: '1049388848315',
    projectId: 'fir-casa0015-app',
    storageBucket: 'fir-casa0015-app.appspot.com',
    iosClientId: '1049388848315-mpu69nrlf9d19dl7fanln1820mfo7utc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCasa0015MobileApp',
  );
}
